app:
    resource: "@AppBundle/Controller/"
    type:     annotation

list:
    path: "/list"
    defaults:  { _controller: AppBundle:List:index }

settings:
    path: "/settings"
    defaults:  { _controller: AppBundle:Settings:index }